#!/bin/bash

# Программа вывода страницы с информацией о системе

title="System Information Report"
echo "<HTML>
	<HEAD>
		<TITLE>$title</TITLE>
	</HEAD>
	<BODY>
		<H1>$title</H1>
	</BODY>
</HTML>"








